### ISSUE TITLE
openvino/workbench 2022.1 fails to run benchmark-app in device MYRIAD.3.2-ma2480

### ISSUE THREAD

**Issue by dnoliver** [openvinotoolkit/workbench#83]
To reproduce, you need a host with that kind of device (DevCloud have them)

1. Create a project, import and convert a model
2. Select the environment with the target device 
3. Import the dataset
4. Run the project

Expected Result: project should run fine, given that the device is a valid target for benchmark app
Actual Result: project fails, with the error specified in the log below.

Screenshot shows a device with those properties:

![image](https://user-images.githubusercontent.com/7730267/174127744-2ed5018c-ba63-4c9c-ac67-3f3903249cdc.png)

Screenshot shows the result of the project execution:

![image](https://user-images.githubusercontent.com/7730267/174128627-371a093a-c390-42b2-afb9-0d9113820a49.png)

Job log shows the parameters passed to benchmark app. nstreams is not properly configured. I have verified that passing nstreams=1 makes the benchmark-app happy (looks like it doesn't default gracefully when the device is MYRIAD.3.2-ma2480)

```
Checking system requirements.
Checking the OS of the target.
Ubuntu 18.04.6 LTS is supported.
The home directory is /home/u79729.
Checking the Python version.
Python 3.6 is supported.
Checking the pip version.
Pip 21 is supported.
Checking internet connection.
The target has internet connection.
Configuring Python environment.
Requirement already satisfied: semver==2.13.0 in /usr/local/lib/python3.6/dist-packages (2.13.0)
benchmark_app is working correctly.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

accuracy_check is working correctly.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

pot is working correctly.
Environment validation completed successfully
Checking paswordless sudo.
sudo: a password is required
The target does not have the sudo package installed.
USB rules are not loaded to this target.
PYTHON_ENVIRONMENT_PATH=/opt/python-env/dlwb_2022_1
Full CPU name is Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz
CPU cores number: 12
CPU frequency range: 1.0-2.4 GHz
SCRIPT SUCCESSFULLY FINISHED

-----------------------------------------------

[setupvars.sh] OpenVINO environment initialized
[NEW STAGE] 0;0
[RUN COMMAND] "benchmark_app" -m "/home/u79729/.dev_cloud_service/dcs_wb_5669/bundles/20220616165856/job_bundle/model/face-detection-0200.xml" -i "/home/u79729/.dev_cloud_service/dcs_wb_5669/bundles/20220616165856/job_bundle/dataset" -d "MYRIAD.3.2-ma2480"   -t "20" --report_type "no_counters" --report_folder "/home/u79729/.dev_cloud_service/dcs_wb_5669/bundles/20220616165856/job_artifacts/0_0" -pc --exec_graph_path "/home/u79729/.dev_cloud_service/dcs_wb_5669/bundles/20220616165856/job_artifacts/0_0/exec_graph.xml"
[Step 1/11] Parsing and validating input arguments

[ WARNING ]  -nstreams default value is determined automatically for a device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.

[Step 2/11] Loading OpenVINO

[ WARNING ] PerformanceMode was not explicitly specified in command line. Device MYRIAD.3.2-ma2480 performance hint will be 
set to THROUGHPUT.

[ INFO ] OpenVINO:

         API version............. 2022.1.0-7019-cdb9bec7210-releases/2022/1

[ INFO ] Device info

         MYRIAD

         openvino_intel_myriad_plugin version 2022.1

         Build................... 2022.1.0-7019-cdb9bec7210-releases/2022/1



[Step 3/11] Setting device configuration

[ WARNING ] -nstreams default value is determined automatically for MYRIAD.3.2-ma2480 device. Although the automatic selection usually provides a reasonable performance, but it still may be non-optimal for some cases, for more information look at README.

[ ERROR ] [ GENERAL_ERROR ]

/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu18/b/repos/openvino/src/plugins/intel_myriad/common/src/configuration/options/ov_throughput_streams.cpp:29 unexpected NUM_STREAMS option value "-1", only not negative numbers are supported

Traceback (most recent call last):

  File "/opt/python-env/dlwb_2022_1/lib/python3.6/site-packages/openvino/tools/benchmark/main.py", line 223, in run

    benchmark.set_config(config)

  File "/opt/python-env/dlwb_2022_1/lib/python3.6/site-packages/openvino/tools/benchmark/benchmark.py", line 53, in set_config

    self.core.set_property(device, config[device])

RuntimeError: [ GENERAL_ERROR ]

/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu18/b/repos/openvino/src/plugins/intel_myriad/common/src/configuration/options/ov_throughput_streams.cpp:29 unexpected NUM_STREAMS option value "-1", only not negative numbers are supported

[ INFO ] Statistics report is stored to /home/u79729/.dev_cloud_service/dcs_wb_5669/bundles/20220616165856/job_artifacts/0_0/benchmark_report.csv

JOB SCRIPT ERROR: Remote job failed, code: 1
```

**Comment by artyomtugaryov** [comment]
Hello, @dnoliver! Thank you for using the tool.
Looks like the DL Workbench presents HDDL device as a bunch of MYRIADs in the DevCloud. Thank you for reporting the issue, we will investigate it
